version: "3.9"

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  app:
    container_name: jarvis-client
    image: jarvis-client:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 7410
    ports:
      - "7410:7410"
    environment:
      FASTAPI_ENV: production
      LOG_LEVEL: INFO
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      DASHBOARD_PORT: 9181
    depends_on:
      - redis
      - workers
      - scheduler

  workers:
    image: jarvis-client:latest
    command: rq worker
    environment:
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - redis

  scheduler:
    container_name: scheduler
    image: jarvis-client:latest
    command: rqscheduler -i 1
    environment:
      RQ_REDIS_HOST: "redis"
      RQ_REDIS_PORT: 6379
    depends_on:
      - redis
      - workers

  dashboard:
    container_name: dashboard
    image: jarvis-client:latest
    command: rq-scheduler-dashboard
    ports:
      - "9181:9181"
    environment:
      RQ_SCHEDULER_DASHBOARD_REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - redis
      - workers
      - scheduler

  # listener: