version: "3.9"

services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  # workers:

  app:
    build:
      context: .
      dockerfile: Dockerfiles/server.dockerfile
    container_name: "jarvis-client"
    ports:
      - "8000:8000"
    environment:
      FASTAPI_ENV: production
      LOG_LEVEL: INFO
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6370
    depends_on:
      - redis
      - workers

  # dashboard: