version: "3.9"

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  workers:
    container_name: workers
    build:
      context: .
      dockerfile: ./dockerfiles/workers.dockerfile
    environment:
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - redis

  scheduler:
    container_name: scheduler
    build:
      context: .
      dockerfile: ./dockerfiles/scheduler.dockerfile
    environment:
      RQ_REDIS_INTERVAL: 1
      RQ_REDIS_HOST: "redis"
      RQ_REDIS_PORT: 6379
    depends_on:
      - redis
      - workers

  dashboard:
    container_name: dashboard
    build:
      context: .
      dockerfile: ./dockerfiles/dashboard.dockerfile
    ports:
      - "9181:9181"
    environment:
      RQ_SCHEDULER_DASHBOARD_REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - redis
      - workers
      - scheduler

  app:
    container_name: jarvis-client
    build:
      context: .
      dockerfile: ./dockerfiles/client.dockerfile
    ports:
      - "8000:8000"
    environment:
      FASTAPI_ENV: production
      LOG_LEVEL: INFO
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    depends_on:
      - redis
      - workers
      - scheduler

  # listener: